[package]
name = "tabled"
version = "0.1.2"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"
description = "An easy to use library for pretty print tables of Rust `struct`s and `enum`s."
repository = "https://github.com/zhiburt/tabled"
license = "MIT"
keywords = ["sheet", "table", "graphics", "terminal"]
categories = ["text-processing", "visualization"]
readme = "README.md"

[badges]
travis-ci = { repository = "https://github.com/zhiburt/tabled", branch = "master" }
coveralls = { repository = "https://github.com/zhiburt/tabled", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[features]
color = ["papergrid/color"]

[dependencies]
tabled_derive = "0.1.4"
papergrid = "0.1.9"

[dev-dependencies]
colored = "2.0.0"
