[package]
name = "tabled"
version = "0.7.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"
description = "An easy to use library for pretty print tables of Rust `struct`s and `enum`s."
repository = "https://github.com/zhiburt/tabled"
homepage = "https://github.com/zhiburt/tabled"
documentation = "https://docs.rs/tabled"
license = "MIT"
keywords = ["table", "print", "pretty-table", "format", "terminal"]
categories = ["text-processing", "visualization"]
readme = "README.md"

[workspace]
members = [
    "papergrid",
    "tabled_derive",
    "examples/table_with_terminal_width",
    "examples/show",
    "benches"
]

[badges]
travis-ci = { repository = "https://github.com/zhiburt/tabled", branch = "master" }
coveralls = { repository = "https://github.com/zhiburt/tabled", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[features]
color = ["papergrid/color", "ansi-str"]

[dependencies]
tabled_derive = { path = "./tabled_derive" }
papergrid = { path = "./papergrid" }
ansi-str = { git = "https://github.com/zhiburt/ansi-str", branch = "master", optional = true }
unicode-width = "0.1.9"

[dev-dependencies]
owo-colors = "3.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[[example]]
name = "colored_borders"
required-features = ["color"]

[[example]]
name = "color"
required-features = ["color"]

[[example]]
name = "rename_all"
path = "examples/derive/rename_all.rs"

[[example]]
name = "rename"
path = "examples/derive/rename.rs"

[[example]]
name = "order"
path = "examples/derive/order.rs"

[[example]]
name = "skip"
path = "examples/derive/skip.rs"

[[example]]
name = "inline"
path = "examples/derive/inline.rs"

[[example]]
name = "inline_enum"
path = "examples/derive/inline_enum.rs"

[[example]]
name = "display_with"
path = "examples/derive/display_with.rs"
