[package]
name = "papergrid"
version = "0.1.7"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"
description = "Papergrid is a library which provide an paper like table printing"
repository = "https://github.com/zhiburt/tabled"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
color = ["console"]

[dependencies]
textwrap = "0.13.4"
console = { version = "0.14.1", optional = true }

[dev-dependencies]
colored = "2.0.0"
